version: '3.13'
services:
  N-Labot:
    build: .
    image: python:3.13-slim
    container_name: N-Labot
    working_dir: /apps
    volumes:
      - ./apps:/apps
      - bot_data:/data
    env_file:
      - .env
    command: python /apps/bot.py
    restart: always
volumes:
  bot_data: